version: '3.4'

services:
  
 postgres:
  image: postgres:latest
  restart: always
  environment:
    POSTGRES_DB: "MFC"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
    PGDATA: "/var/lib/postgresql/data/pgdata"
  volumes:
    - pg-data:/var/lib/postgresql/data
    - ./MFC.sql:/docker-entrypoint-initdb.d/init.sql
  ports:
    - "5432:5432"
 
 api:
  image: webapi
  restart: always
  build:
    context: .
    dockerfile: WebApi/Dockerfile
  ports:
    - "8080:80"
#    - "7132:443"
  depends_on: [ "postgres" ]
  environment:
    DATABASE_CONNECT: "Server=postgres;Port=5432;Database=MFC;User Id=postgres;Password=postgres"
    ASPNETCORE_HTTP_PORTS: "80"
#    ASPNETCORE_HTTPS_PORTS: "443"
#    ASPNETCORE_URLS: "https://+;http://+"
#    ASPNETCORE_Kestrel__Certificates__Default__Password: "1234"
#    ASPNETCORE_Kestrel__Certificates__Default__Path: "https/aspnetapp.pfx"
#    ASPNETCORE_ENVIRONMENT: "Development"
     
 pgadmin:
  container_name: pgadmin
  image: dpage/pgadmin4:7.2
  restart: always
  environment:
    PGADMIN_DEFAULT_EMAIL: admin@example.com
    PGADMIN_DEFAULT_PASSWORD: postgres
  volumes:
    - pgadmin-data:/var/lib/pgadmin
  ports:
    - "5050:80"
  depends_on: ["postgres", "api"]

volumes:
  pgadmin-data:
  pg-data:
   